// Blog posts. Dependency-free: each post's `body` is an array of blocks
// ({ t: "p" | "h2" | "ul", c }) rendered by BlogPost.jsx — no markdown lib,
// prerender-safe. Add a new post by adding an object here (newest first).
export const posts = [
  {
    slug: "choosing-coding-bootcamp-bengaluru-parents-guide",
    title: "How to choose a coding bootcamp in Bengaluru — a guardian's guide",
    description:
      "A short, honest guide for parents comparing coding institutes in Bengaluru: what to look for, what to ignore, and the questions that actually reveal quality.",
    date: "2026-09-04",
    author: "Rest Coder Academy",
    readMinutes: 7,
    body: [
      { t: "p", c: "Every parent in Bengaluru we speak with has the same two problems: dozens of coding institutes look identical from their websites, and the fee for a full-stack course can range from ₹15,000 to ₹1,50,000 for what claims to be the same outcome. This guide is what we tell parents in our own counselling calls — an honest checklist that cuts through the noise." },
      { t: "h2", c: "What to look for" },
      { t: "p", c: "The single strongest signal of a good coding course is not the syllabus, the classroom, or the marketing — it is whether the institute will name specific graduates and the specific companies they joined. If they cannot, do not assume the placement claim is real. If they can, verify one or two on LinkedIn." },
      { t: "p", c: "Beyond that, five things matter more than anything else on their brochure:" },
      { t: "ul", c: [
        "Live classes with a real trainer — not recorded videos labelled \"self-paced\". Most students who drop off never restart the recording.",
        "The trainer's actual profile — name, current or last job, LinkedIn, at least one verifiable piece of work. If the institute hides this, they have a reason.",
        "Project-based assessment — your child builds real software during the course, not \"exercises\". Ask to see one graduate's project GitHub.",
        "Progress visibility for you — you should see weekly attendance and progress, not \"we'll let you know if there is a problem\".",
        "A written refund policy — a good institute will show you one on day zero.",
      ] },
      { t: "h2", c: "What to ignore" },
      { t: "p", c: "Air-conditioned classrooms, glossy brochures, big banners at metro stations, and the phrase \"industry-recognised certification\" (there is no such thing that actually helps in Indian hiring). Also, be careful of the two extremes: a fee that is very low usually means the course is prerecorded video with no real trainer time, and a very high fee usually means most of your money is going to advertising and franchise cuts, not to your child's learning." },
      { t: "h2", c: "Questions worth asking" },
      { t: "ul", c: [
        "\"Can you send me the LinkedIn profiles of three of your recent graduates?\"",
        "\"Who exactly will be teaching this batch, and what have they built or shipped?\"",
        "\"Can I see one week of your syllabus in detail, not just the topic list?\"",
        "\"What happens if my child falls behind or drops off — do I get told, and when?\"",
        "\"What does placement support actually mean? Do you refer, prep, or just introduce?\"",
      ] },
      { t: "p", c: "How they answer tells you more than the brochure ever will. A confident institute will answer specifically. A weak one will pivot to a sales pitch." },
      { t: "h2", c: "The tour that tells you the truth" },
      { t: "p", c: "Ask to visit during an actual class, not on an appointment day. Look at three things: whether every student is actually working (not on their phone), whether the trainer is walking around answering questions, and whether the class is under 25 people. A crowded room where nobody is engaged is a warning, not an excuse." },
      { t: "p", c: "If you would like a straight conversation about your child's background and goals — including candid comparisons to other institutes you are considering — come talk to us. We will not oversell." },
    ],
  },
  {
    slug: "non-cs-background-to-full-stack-developer",
    title: "From a non-CS background to full-stack developer — an honest timeline",
    description:
      "How long it really takes to switch to full-stack development from a non-CS background, what each phase looks like, and how to know if you're on track.",
    date: "2026-09-04",
    author: "Rest Coder Academy",
    readMinutes: 6,
    body: [
      { t: "p", c: "A large share of the students we work with did not come from computer science. Commerce, mechanical, biotech, arts, testing, support, banking — the switch is common, and it works. But the timelines being sold online (\"become a developer in 3 months!\") are dishonest. Here is what it actually looks like." },
      { t: "h2", c: "Month 0–1: fundamentals" },
      { t: "p", c: "You learn one language, deeply. Not two, not five. Variables, functions, control flow, arrays, objects, and enough of the standard library to build small programs. If your course is any good, you write dozens of tiny programs in this phase — not read about them. Expect to feel slow. Everyone feels slow. This is the phase most self-learners quietly quit in." },
      { t: "h2", c: "Month 2–3: your first stack" },
      { t: "p", c: "You add a framework (Spring Boot, Django, or Node/Express) and a database, and you start building small applications that store and retrieve real data. By the end of this phase you should have built at least one CRUD application from scratch that you did not follow along to from a video. Something ugly is fine — original is what matters." },
      { t: "h2", c: "Month 4: the front end" },
      { t: "p", c: "HTML, CSS, JavaScript, then a framework (usually React). By the end of this phase you should be able to build a full-stack application — a front end that talks to an API you wrote, backed by a database — end-to-end." },
      { t: "h2", c: "Month 5: shipping" },
      { t: "p", c: "This is the phase most courses skip and most learners never finish on their own. You deploy your work somewhere real: a domain, a cloud host, a database that survives a restart. You add authentication that isn't broken, a payment integration, and error tracking. If you have never deployed anything, you are not a developer yet — you are a student. Shipping is the ceiling most people never cross without a structured push." },
      { t: "h2", c: "Month 6: interview readiness" },
      { t: "p", c: "You revise data structures and algorithms just enough to survive the coding round (not to become a competitive programmer), you polish two or three projects on your GitHub, and you start applying. Most switchers we work with land their first role somewhere between month 6 and month 8. A lucky few land in month 4. That is the honest range." },
      { t: "h2", c: "How to know you are on track" },
      { t: "ul", c: [
        "You can explain what a request does from browser to database, out loud, in your own words.",
        "You have shipped one thing publicly — even something ugly — that a stranger could use.",
        "You are debugging by reading error messages and stack traces, not by asking a chatbot to fix it.",
        "You have written a README for a project that another beginner could follow.",
      ] },
      { t: "p", c: "If you are somewhere on this timeline and want structure around the parts that are hard to do alone — the deploying, the debugging, the second and third projects — that is exactly what a live, project-based course gives you. Talk to a counsellor if you would like a plan tailored to where you already are." },
    ],
  },
  {
    slug: "live-coding-classes-vs-recorded-videos",
    title: "Live coding classes vs recorded videos — does it actually matter?",
    description:
      "The honest difference between live and recorded coding classes: completion rates, feedback loops, and why the cheap-recorded-video model rarely leads anywhere.",
    date: "2026-09-03",
    author: "Rest Coder Academy",
    readMinutes: 5,
    body: [
      { t: "p", c: "Every online coding course sells the same convenience: watch when you want, learn at your pace, complete on your schedule. It is a very seductive pitch. It is also the reason most online courses have completion rates in the low single digits. The uncomfortable truth about live vs recorded coding classes is this: it does not matter what you paid, it matters whether you finished." },
      { t: "h2", c: "What live classes actually give you" },
      { t: "p", c: "Three things a recording cannot: a real person who notices when you stop showing up, immediate feedback when your code is wrong for a reason you cannot see, and a room full of people whose expectation of your presence makes you keep showing up. That last one sounds small — it is not. It is the single biggest predictor of whether you finish." },
      { t: "h2", c: "Where recorded videos are fine" },
      { t: "p", c: "Quick reference for syntax you have forgotten. Learning a specific library's API. Getting a fast overview of a concept before you build on it. Free tutorial content on YouTube is genuinely great for these. What recorded content is not good for: your first exposure to a topic you have to actually master, or building the habit of shipping software." },
      { t: "h2", c: "Where the money goes" },
      { t: "p", c: "A recorded-video course can be sold to unlimited students at almost no marginal cost — which is why they can price at ₹5,000 to ₹20,000. A live cohort with a real trainer is priced by the trainer's time. When you see a \"live\" course sold at recorded-video prices, the \"live\" part is almost always doubtful: a huge classroom, a trainer racing through a slide deck, no real interaction, no follow-up." },
      { t: "h2", c: "How to test whether a live course is actually live" },
      { t: "ul", c: [
        "Ask what the maximum batch size is. Under 25 is a real cohort. Over 50 is a lecture hall.",
        "Ask whether trainers review student projects during the course, and how often.",
        "Ask what happens if you miss a class or fall behind — do you get a call, or a recording link?",
        "Ask to sit in on one real class before enrolling. A confident course will let you.",
      ] },
      { t: "h2", c: "The right answer for most people" },
      { t: "p", c: "If your goal is to actually change what you do for a living — not to add \"coding course\" to your resume — a live cohort with real accountability finishes you. Free videos plus solo grinding works too, but the drop-off rate is brutal. Only a small fraction of self-learners cross the finish line, and that fraction almost always has strong external accountability from somewhere else. If you would like a straight opinion on what would suit you specifically, come talk to a counsellor." },
    ],
  },
  {
    slug: "what-placement-support-actually-means",
    title: "What \"placement support\" actually means — and how to spot fake claims",
    description:
      "\"100% placement\" is one of the most misused phrases in Indian coding education. Here's what real placement support looks like — and the questions that expose fake claims.",
    date: "2026-09-03",
    author: "Rest Coder Academy",
    readMinutes: 6,
    body: [
      { t: "p", c: "\"100% placement\" is one of the most misused phrases in Indian coding education. Almost nobody who advertises it actually means \"every student who finished got a job\" — most mean \"we referred everyone at least once\", or \"here is a certificate that says you completed the course\". Here is what real placement support actually looks like, and the questions that separate real from theatre." },
      { t: "h2", c: "What real placement support does" },
      { t: "p", c: "There is no magic here. Real placement support is a small set of unglamorous things done well, every batch:" },
      { t: "ul", c: [
        "Portfolio review — one-on-one, on your actual GitHub, not a template.",
        "Resume review — specific to the role you are targeting, not a generic template.",
        "Mock interviews — technical and behavioural, with someone who has actually interviewed candidates.",
        "Referrals into a maintained hiring network — companies the institute has an actual relationship with, not a shared job board.",
        "Post-placement follow-up — many students need help with the first 30 days on the job. Good institutes stay in touch.",
      ] },
      { t: "h2", c: "What fake placement support looks like" },
      { t: "p", c: "A vague \"placement cell\" that turns out to be a WhatsApp group with a few links a week. A \"guaranteed job\" clause that turns out to be a certificate. A partnership page with 40 company logos and zero named graduates. A tour where nobody can name a specific student who was hired last quarter." },
      { t: "h2", c: "The three questions that expose it" },
      { t: "p", c: "Ask these before you pay. Answers matter more than the way they are asked:" },
      { t: "ul", c: [
        "\"Can you show me the LinkedIn profiles of five graduates from the last two batches?\" — a real institute has this ready.",
        "\"What percentage of your last batch was placed, and how do you count that?\" — the definition of \"placed\" is where dishonest numbers hide. A serious answer will define it clearly.",
        "\"What is the median salary of a placed graduate?\" — median, not average. Averages are how you hide low outliers behind one big-package outlier.",
      ] },
      { t: "h2", c: "Why we are careful about the numbers we quote" },
      { t: "p", c: "We deliberately do not publish a \"100% placement\" claim, because the honest number is never 100% — some students take a break, some pivot to further study, some take longer than the visible window. What we do publish is named graduates and their companies, on our Placements page, so that anyone can verify. If you would like a candid conversation about what our support looks like for someone with your background, talk to a counsellor." },
    ],
  },
  {
    slug: "java-vs-python-full-stack",
    title: "Java vs Python for full-stack: which should you learn first?",
    description:
      "A straight answer for beginners choosing between a Java and a Python full-stack path — what each is good at, who hires for it, and how to decide.",
    date: "2026-09-02",
    author: "Rest Coder Academy",
    readMinutes: 5,
    body: [
      { t: "p", c: "If you're starting out, \"Java or Python?\" is usually the first wall you hit. The honest answer: both lead to jobs, and the language matters less than whether you can actually build and ship something. But they do pull toward different work, so here's how to choose without overthinking it." },
      { t: "h2", c: "What each is actually good at" },
      { t: "p", c: "Java is the workhorse of large, long-lived enterprise systems — banking, insurance, big product companies. It's strict, verbose, and that strictness is exactly why big teams like it: the compiler catches a lot before code ever runs. A Java full-stack path typically means Core & Advanced Java, Spring/Spring Boot, Hibernate, REST APIs, and a front end." },
      { t: "p", c: "Python is faster to write and reads almost like English, which is why it dominates data, scripting, automation, and AI, and is very strong for web too via Django. A Python full-stack path means Python, Django, REST APIs, and a modern front end. If you think you might drift toward data or AI later, Python gives you a head start." },
      { t: "h2", c: "Who's hiring for each" },
      { t: "p", c: "In most Indian cities, Java has the larger raw volume of openings — services companies and product teams run enormous Java codebases. Python roles are growing fast and skew toward startups, data, and AI-heavy teams. Neither is a dead end; both have healthy demand in 2026." },
      { t: "h2", c: "So how do you actually decide?" },
      { t: "ul", c: [
        "Want the widest set of openings and don't mind strictness? Start with Java.",
        "Prefer to move fast, or curious about data/AI down the line? Start with Python.",
        "Genuinely torn? Pick either. The concepts — APIs, databases, HTTP, a front end, deploying to production — carry across. Learning your second language later is a matter of weeks, not months.",
      ] },
      { t: "h2", c: "The thing that actually gets you hired" },
      { t: "p", c: "Whichever you pick, employers don't hire a language — they hire someone who has built and shipped real things. That's why our Java and Python full-stack courses are project-based and live: you build working software, not slides, and ship it. If you'd like help choosing based on your background and goals, talk to a counsellor — it's a five-minute conversation that saves months." },
    ],
  },
  {
    slug: "is-a-coding-course-worth-it-2026",
    title: "Is a coding course worth it in 2026? An honest look",
    description:
      "Coding courses get a bad rap for good reasons. Here's when one is genuinely worth it, when it isn't, and the questions to ask before you pay.",
    date: "2026-09-01",
    author: "Rest Coder Academy",
    readMinutes: 6,
    body: [
      { t: "p", c: "Plenty of people have paid for a coding course and gotten nothing out of it. So it's a fair question: in 2026, with free tutorials everywhere and AI that writes code, is a paid course still worth it? The honest answer is \"sometimes\" — and it depends far more on the course than on you." },
      { t: "h2", c: "When a course is NOT worth it" },
      { t: "ul", c: [
        "It's all recorded videos and theory. You can get that free on YouTube.",
        "You never build anything real — just follow along and copy exercises.",
        "There's no accountability: nobody checks whether you're attending, learning, or progressing.",
        "\"Placement\" is a vague promise with no named students or companies behind it.",
      ] },
      { t: "p", c: "If a course looks like this, save your money. Self-study plus a few real projects will beat it." },
      { t: "h2", c: "When a course IS worth it" },
      { t: "p", c: "A good course buys you three things free tutorials can't: structure, feedback, and momentum. A live cohort with a real trainer means you're building actual software, getting your work reviewed, and being kept accountable so you don't quietly drift off in week three — which is where most self-learners stall." },
      { t: "p", c: "The best ones also close the loop to a job: real placement support, and honesty about outcomes. Ask to see named graduates and where they actually work." },
      { t: "h2", c: "Does AI change the answer?" },
      { t: "p", c: "AI writes code, but it doesn't yet decide what to build, debug a broken production system, or take responsibility for shipping. Those judgment skills are exactly what get you hired — and they come from building real things with feedback, not from watching videos. If anything, AI raises the bar on \"can you actually ship?\", which is what a good, project-based course trains." },
      { t: "h2", c: "Questions to ask before you pay" },
      { t: "ul", c: [
        "Will I build and ship real projects, or just do exercises?",
        "Is it live, with a real trainer I can verify?",
        "How do you keep students accountable and on track?",
        "Can you show me named graduates and the companies they joined?",
        "What exactly does \"placement support\" mean?",
      ] },
      { t: "p", c: "That last set is how we'd want you to judge us too. Our courses are live and project-based, guardians can see a student's progress every week, and our placements page lists real graduates by name and company. If that's the kind of course you're after, come talk to us." },
    ],
  },
];

export function getPost(slug) {
  return posts.find((p) => p.slug === slug) || null;
}
